create table if not exists public.users (
  id uuid primary key references auth.users(id) on delete cascade,
  username text unique not null,
  display_name text not null,
  email text not null,
  created_at timestamptz not null default now()
);

create or replace function public.handle_new_user()
returns trigger as $$
begin
  insert into public.users (id, username, display_name, email)
  values (
    new.id,
    coalesce(new.raw_user_meta_data->>'username', split_part(new.email, '@', 1)),
    coalesce(new.raw_user_meta_data->>'display_name', split_part(new.email, '@', 1)),
    new.email
  );
  return new;
end;
$$ language plpgsql security definer set search_path = public;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
  after insert on auth.users
  for each row execute procedure public.handle_new_user();

create table if not exists public.history (
  id bigint generated by default as identity primary key,
  user_id uuid not null references public.users(id) on delete cascade,
  anime_id text not null,
  episode_id text not null,
  provider text not null default 'anilist',
  source text,
  position double precision not null default 0,
  duration double precision not null default 0,
  completed boolean not null default false,
  anime_title text,
  anime_cover text,
  episode_number integer,
  episode_title text,
  updated_at timestamptz not null default now(),
  unique (user_id, anime_id, episode_id)
);

alter table if exists public.history drop constraint if exists history_user_id_anime_id_key;
alter table if exists public.history drop constraint if exists history_user_anime_episode_key;
alter table if exists public.history add constraint history_user_anime_episode_key unique (user_id, anime_id, episode_id);

create index if not exists idx_history_user_completed on public.history (user_id, completed);

create table if not exists public.favorites (
  id bigint generated by default as identity primary key,
  user_id uuid not null references public.users(id) on delete cascade,
  anime_id text not null,
  provider text not null default 'anilist',
  anime_title text,
  anime_cover text,
  created_at timestamptz not null default now(),
  unique (user_id, anime_id, provider)
);

create index if not exists idx_favorites_user on public.favorites (user_id);

create table if not exists public.user_settings (
  user_id uuid primary key references public.users(id) on delete cascade,
  settings jsonb not null default '{}'::jsonb,
  updated_at timestamptz not null default now()
);

create table if not exists public.trackers (
  id bigint generated by default as identity primary key,
  user_id uuid not null references public.users(id) on delete cascade,
  provider text not null,
  username text,
  token text,
  updated_at timestamptz not null default now(),
  unique (user_id, provider)
);

create table if not exists public.notifications (
  id bigint generated by default as identity primary key,
  user_id uuid not null references public.users(id) on delete cascade,
  anime_id text not null,
  provider text not null default 'anilist',
  anime_title text,
  anime_cover text,
  created_at timestamptz not null default now(),
  unique (user_id, anime_id, provider)
);

alter table if exists public.users enable row level security;
alter table if exists public.history enable row level security;
alter table if exists public.favorites enable row level security;
alter table if exists public.user_settings enable row level security;
alter table if exists public.trackers enable row level security;
alter table if exists public.notifications enable row level security;

drop policy if exists "Public profiles are viewable by everyone" on public.users;
drop policy if exists "Users can update own profile" on public.users;
create policy "Public profiles are viewable by everyone" on public.users
  for select using (true);
create policy "Users can update own profile" on public.users
  for update using (auth.uid() = id);

drop policy if exists "Manage own history" on public.history;
drop policy if exists "Manage own favorites" on public.favorites;
drop policy if exists "Manage own settings" on public.user_settings;
drop policy if exists "Manage own trackers" on public.trackers;
drop policy if exists "Manage own notifications" on public.notifications;
create policy "Manage own history" on public.history
  using (auth.uid() = user_id);
create policy "Manage own favorites" on public.favorites
  using (auth.uid() = user_id);
create policy "Manage own settings" on public.user_settings
  using (auth.uid() = user_id);
create policy "Manage own trackers" on public.trackers
  using (auth.uid() = user_id);
create policy "Manage own notifications" on public.notifications
  using (auth.uid() = user_id);
